<?php
/* This file was automatically generated by the `grunt public-cachebuster` command (Sun Jun 03 2018 18:07:49 GMT+0000 (UTC)). */
return array(
	'es6-shim' => '0.35.3',
	'es7-shim' => '6.0.0',
	'i18n-react' => '0.6.4',
	'immer' => '1.2.1',
	'mobx' => '4.2.0',
	'mobx-state-tree' => '2.0.4',
	'react' => '16.3.2',
	'react-aiot' => '1.2.11',
	'react-dom' => '16.3.2',
	'sortablejs' => '1.7.0'
);
